site_name: uavsar-lidar-ml-project2
site_description: ML-based InSAR models for snow depth estimation in the central mountains of ID.
site_author: Ibrahim-Ola
site_url: https://Ibrahim-Ola.github.io/uavsar-lidar-ml-project2
repo_url: https://github.com/Ibrahim-Ola/uavsar-lidar-ml-project2

copyright: "Copyright &copy; 2024 - 2024 Ibrahim Alabi"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/Ibrahim-Ola/uavsar-lidar-ml-project2/issues
    - Examples:
        - examples/intro.ipynb
    - API Reference:
          - insarml module: insarml.md
          - common module: common.md
